name: run-mh_style
on: [push]
jobs:
  run-mh_style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - run: pip3 install miss_hit
      - run: mh_style
